name: Github Actions Example  //sample
on:
  pull_request:
    types: [open]
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - name: Install dependencies
      run: npm install
    - name: Test project
      run: npm test
